## ROBUSTNESS of the ML methods in determining the important features for two training set sizes ##

## Compare for each cross-validation scheme ##

## 1) 80:20

# First method. lightgbm
setwd("/home/uni08/jubin1/Data/GenomesToFields/G2F20142018/ML_PREDICTIONS/Heslot_scheme/lightgbm/results_index_20")

##Two aspects: compare the robustness across bootstrap samples, and robustness across years
features_imp_lightgbm_80_20<-list()
for (i in 1:30) {
  features_imp_lightgbm_80_20[[i]]<-readRDS(paste0('final_list_results_index',i,'geno_info_PCs_G+WC+SC+Lon+Lat_yld_bu_ac_tuning_method_random-CV.RDS'))['varimps']

}


## Computing the robustness, by taking into account different k features used, using the pair-wised Jaccard index employed in Saeys et al. 2008 ("Feature Selection Using Ensemble Feature Selection Techniques")
library(reshape2)
library(dplyr)
library(vegan)


jaccard_average_index<-function(k){
  d_list<-list()
  for (i in 1:30) {
    #features_imp_lightgbm_80_20[[i]]<- features_imp_lightgbm_80_20[[i]][order( features_imp_lightgbm_80_20[[i]][,'Gain']),]
    d_list[[i]]<-as.data.frame(features_imp_lightgbm_80_20[[i]]) %>% top_n(k,varimps.Gain)
    d_list[[i]]$dataset<-i
    d_list[[i]]<-d_list[[i]][,c('dataset','varimps.Feature')]
    
  }
  d_list2<-do.call(rbind,d_list)
  
  abs_pres<-dcast(d_list2, dataset~varimps.Feature, length)
  
  row.names(abs_pres)<-abs_pres[,1]
  
  abs_pres<-abs_pres[,-1]
  abs_pres<-as.matrix(abs_pres)
  
  indexes_jaccard<-1-vegdist(as.matrix(abs_pres),method='jaccard')  
  return(list(indexes_jaccard,mean(indexes_jaccard)))    
}
  
k_values <- vector()
for (m in seq(1,400,by=1)) {
  print(m)
  k_values[m] <- jaccard_average_index(k=m)[[2]]
  print(k_values[m])
}



saveRDS(k_values,'/home/uni08/jubin1/Data/GenomesToFields/G2F20142018/ML_PREDICTIONS/Heslot_scheme/kvalues_robustness_jaccard.RDS')
pdf('/home/uni08/jubin1/Data/GenomesToFields/G2F20142018/ML_PREDICTIONS/Heslot_scheme/lightgbm_kvalues.pdf',width = 7,height = 6)

plot(x=seq(1,400,by=1),y=k_values,type = 'l',cex.main=0.75,ylab = 'Robustness',xlab = 'Number of best features considered',main='Model coherence in feature importance ranking assessed via Robustness (Jaccard index).\n Each line corresponds to the mean values of the robustness distributions, over all the paiwise similarity comparisons of feature importance lists.\n For each model, 30 different lists of feature importance are considered (using the splits of the original dataset generated by the cross-validation scheme 2).')
legend(x=320,y=0.45,legend = c('LightGBM - gain'),cex=0.65,lty = 1)
dev.off()
